In [ ]:
import pandas as pd

In [ ]:
# lord the dadaset
df = pd.read_csv('walmartcsv.csv')

In [ ]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,"$16,43,690.90",0,42.31,$2.57,211.096358,8.106
1,1,12-02-2010,"$16,41,957.44",1,38.51,$2.55,211.242170,8.106
2,1,19-02-2010,"$16,11,968.17",0,39.93,$2.51,211.289143,8.106
3,1,26-02-2010,"$14,09,727.59",0,46.63,$2.56,211.319643,8.106
4,1,05-03-2010,"$15,54,806.68",0,46.50,$2.63,211.350143,8.106

In [ ]:
df.head

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,"$16,43,690.90",0,42.31,$2.57,211.096358,8.106
1,1,12-02-2010,"$16,41,957.44",1,38.51,$2.55,211.242170,8.106
2,1,19-02-2010,"$16,11,968.17",0,39.93,$2.51,211.289143,8.106

In [ ]:
df.tail(2)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
6433,45,19-10-2012,"$7,18,125.53",0,56.47,$3.97,192.330854,8.667
6434,45,26-10-2012,"$7,60,281.43",0,58.85,$3.88,192.308899,8.667

In [ ]:
df.shape

(6435, 8)

In [ ]:
df.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='object')

In [ ]:
df.info

<bound method DataFrame.info of       Store        Date     Weekly_Sales  Holiday_Flag  Temperature  \
0         1  05-02-2010   $16,43,690.90              0        42.31
1         1  12-02-2010   $16,41,957.44              1        38.51
2         1  19-02-2010   $16,11,968.17              0        39.93
3         1  26-02-2010   $14,09,727.59              0        46.63
4         1  05-03-2010   $15,54,806.68              0        46.50
...     ...         ...              ...           ...          ...
6430     45  28-09-2012    $7,13,173.95              0        64.88
6431     45  05-10-2012    $7,33,455.07              0        64.89
6432     45  12-10-2012    $7,34,464.36              0        54.47
6433     45  19-10-2012    $7,18,125.53              0        56.47
6434     45  26-10-2012    $7,60,281.43              0        58.85

     Fuel_Price         CPI  Unemployment
0         $2.57  211.096358         8.106
1         $2.55  211.242170         8.106
2         $2.51  211.289143         8.106
3         $2.56  211.319643         8.106
4         $2.63  211.350143         8.106
...         ...         ...           ...
6430      $4.00  192.013558         8.684
6431      $3.99  192.170412         8.667
6432      $4.00  192.327265         8.667
6433      $3.97  192.330854         8.667
6434      $3.88  192.308899         8.667

[6435 rows x 8 columns]>